## Pytorch Fundamentals - 00
https://www.youtube.com/watch?v=V_xro1bcAuA&t=2598s

In [48]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


## Pytorch sensors 
Created using `torch.Tensor()`
https://docs.pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html

In [49]:
# Scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [50]:
scalar.ndim  # number of dimensions

0

In [51]:
scalar.item()  # get the value as a standard Python number

7

In [52]:
# Vector tensor
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [53]:
vector.shape

torch.Size([2])

In [54]:
vector.ndim

1

In [55]:
# MATRIX
MATRIX = torch.Tensor([[7, 8], 
                        [9, 10]])
MATRIX

tensor([[ 7.,  8.],
        [ 9., 10.]])

In [56]:
MATRIX.ndim #ndim = elements in array

2

In [57]:
MATRIX[1]

tensor([ 9., 10.])

In [58]:
MATRIX.shape

torch.Size([2, 2])

In [59]:
# TENSOR
TENSOR = torch.Tensor([[[1, 2, 3], 
                        [3, 6, 9], 
                        [2, 4, 5]]])
TENSOR

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 5.]]])

In [60]:
TENSOR.ndim

3

In [61]:
TENSOR.shape

torch.Size([1, 3, 3])

In [62]:
TENSOR[0]

tensor([[1., 2., 3.],
        [3., 6., 9.],
        [2., 4., 5.]])

In [63]:
MY_TENSOR = torch.Tensor([[[[1, 2, 3], 
                            [2, 3, 4],
                            [5, 6, 7]]]])
MY_TENSOR.ndim

4

In [64]:
MY_TENSOR.shape

torch.Size([1, 1, 3, 3])

### Random Tensors
https://youtu.be/V_xro1bcAuA?si=g-yVMRmg3KtPZYm6&t=5865

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [65]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8184, 0.6272, 0.7180, 0.7172],
        [0.3544, 0.0741, 0.9714, 0.5400],
        [0.2455, 0.1292, 0.6825, 0.2549]])

In [66]:
random_tensor.ndim

2

In [67]:
random_tensor.shape

torch.Size([3, 4])

In [68]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # height, width, color_channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones


In [69]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [70]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [71]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [72]:
ones.dtype

torch.float32

### Creating a range of tensors

In [73]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
# Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
**Note** Tensor datatypes is one of the three big errors you'll run into with PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [75]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
dtype=torch.float32, #datatype - precision in computing, how much detail is stored in memory
device=None, # What device is the tensor stored on?
requires_grad=False) # whether or not to track gradients for this tensor's operations
float_32_tensor

tensor([3., 6., 9.])

In [76]:
float_32_tensor.dtype

torch.float32

In [77]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [78]:
d = float_16_tensor * float_32_tensor # becomes float32

## Ints
https://youtu.be/V_xro1bcAuA?si=FeZ6J8jf4MvAp_Zh&t=7409

In [79]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [80]:
y = float_32_tensor * int_32_tensor
y.dtype

torch.float32

### Getting info from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [81]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4495, 0.6048, 0.8725, 0.0307],
        [0.2184, 0.3815, 0.0757, 0.8846],
        [0.5386, 0.1174, 0.9825, 0.2161]])

In [82]:
print(some_tensor)
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

tensor([[0.4495, 0.6048, 0.8725, 0.0307],
        [0.2184, 0.3815, 0.0757, 0.8846],
        [0.5386, 0.1174, 0.9825, 0.2161]])
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [83]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [84]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [85]:
# Divide tensor by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [86]:
# Subtract 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [87]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)  # multiply tensor by 10

tensor([10, 20, 30])

### Matrix Multiplication
https://youtu.be/V_xro1bcAuA?si=-YlZWxh2QmpDqDR-&t=8269

Two main ways of performing multiplication in neural networks and deep learning.

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [88]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [89]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [90]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

### One of the most common erros in deep learning: Shape Errors
There are two rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work 
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [ ]:
#torch.matmul(torch.rand(3, 2), torch.rand(3, 2)) #  this will result in an error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

# Shapes for matrix multiplication - T, Transpose
http://matrixmultiplication.xyz/

In [92]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],   
                         [9, 12]])
# torch.mm(tensor_A, tensor_B)  # torch.mm is torch.matmul - will result in a shape error

# adjust shapes - transpose tensor_B
torch.mm(tensor_A, tensor_B.T)  # .T is transpose

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum etc (tensor aggregation)

In [93]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [94]:
# Find the min
torch.min(x)
x.min()

tensor(0)

In [95]:
# Find the max
torch.max(x)
x.max()

tensor(90)

In [96]:
# Find mean
torch.mean(x.float()) # long wrong datatype for this function
x.type(torch.FloatTensor).mean()

tensor(45.)

In [97]:
# Find median
torch.median(x.float())
x.type(torch.FloatTensor).median()

tensor(40.)

In [98]:
# Find sum
torch.sum(x)
x.sum()

tensor(450)

# Find the positional min and max

In [99]:
x.argmin()  # index of min value

tensor(0)

In [100]:
# Find the position in tensor that has the maximum value
x.argmax()  # index of max value
x[x.argmax()]  # value at max index

tensor(90)

## Reshaping, stacking, squeezing, and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other vertical stack (vstack) or horizontal stock (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [101]:
# Create a tensor
# import torch

x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [108]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)  # add an extra dimension, must keep same number of elements (9) - will work for (9, 1), multiples of size of tensor
x_reshaped, x_reshaped.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [109]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [110]:
# Changing z changes x too because they share the same memory
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [111]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)  # dim=0 stacks on top of each other, dim=1 stacks side by side
x_stacked, x_stacked.shape

(tensor([[5, 5, 5, 5],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6],
         [7, 7, 7, 7],
         [8, 8, 8, 8],
         [9, 9, 9, 9]]),
 torch.Size([9, 4]))

In [ ]:
# https://youtu.be/V_xro1bcAuA?si=0wsltx79eC2Nbr3P&t=11490
# torch.squeeze() - removes all single dimensions from a tensor
x_reshaped, x_reshaped.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [120]:
x_reshaped_squeezed = x_reshaped.squeeze()
x_reshaped_squeezed.shape

torch.Size([9])

In [124]:
# torch.unsqueeze() - adds a single dimension to a tensor at a specified dimension
print(f"Previous target: {x_reshaped_squeezed}")
print(f"Previous shape: {x_reshaped_squeezed.shape}")

# Add an extra dimension
x_reshaped_unsqueezed = x_reshaped_squeezed.unsqueeze(dim=0) # dim=0 adds dimension at front, dim=1 adds dimension at second position
x_reshaped_unsqueezed, x_reshaped_unsqueezed.shape

Previous target: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])


(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [130]:
# torch.permute rearranges the dimensions of a tensor
x_permuted = torch.permute(x_reshaped_unsqueezed, (1, 0))  # switches dimensions 0 and 1
x_permuted, x_permuted.shape


x_original = torch.randn(size=(224, 224, 3))  # height, width, color_channels (R, G, B)

# Permute the original image tensor to rearrange the dimensions to (color_channels, height, width)
x_permuted_image = torch.permute(x_original, (2, 0, 1))  # new order: (3, 224, 224)
x_permuted_image.shape

torch.Size([3, 224, 224])

In [140]:
x_original[0, 0, 0] = 676767
x_original[0, 0, 0], x_permuted_image[0, 0, 0] # change is reflected here too because they share the same memory

(tensor(676767.), tensor(676767.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [1]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)  # reshape to (1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [2]:
# Index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [4]:
# Let's index on the inner bracket (dim=2)
x[0][0][0]

tensor(1)

In [5]:
# You can also use a semicolon to select all dimensions
x[:, 0]

tensor([[1, 2, 3]])

In [6]:
# Get all values of 0th and 1st dimension, but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [7]:
# Get all values of the 0 dimensions but only the 1st index of the 1st and 2nd dimensions
x[:, 1, 1]

tensor([5])

In [8]:
# Get index 0 of 0th and 1st dimensions and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

NumPy is a popular, scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`


In [9]:
# Turning numpy arranys into torch tensors
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.FloatTensor) # float64 -> float32
array, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [10]:
# Default datatype of numpy array is float64 and torch tensor is float32
array.dtype

dtype('float64')

In [11]:
# Change the value of array, what will this do to tensor?
array = array + 1
array, tensor # tensor will not change because the memory is not shared

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [12]:
# Tensor to Numpy array 
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [13]:
# Change the tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor # tensor will not change because the memory is not shared

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility in PyTorch
# Trying to take out the random out of randomness
https://youtu.be/V_xro1bcAuA?si=jUmjI4J0efXL3NR9&t=13330

In short how a neural network learns:
`start with random numbers -> perform tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness

In [14]:
torch.rand(3, 3)

tensor([[0.2664, 0.7299, 0.3404],
        [0.6605, 0.8059, 0.2243],
        [0.8977, 0.4140, 0.7803]])

In [15]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2629, 0.7150, 0.8681, 0.9870],
        [0.7007, 0.4078, 0.2711, 0.3867],
        [0.8238, 0.4671, 0.6785, 0.1774]])
tensor([[0.5321, 0.7319, 0.4460, 0.1015],
        [0.6506, 0.5459, 0.7905, 0.5653],
        [0.4043, 0.7565, 0.9185, 0.3320]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [16]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED) # declard seed before creating tensor eeach time
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPUs (faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory lol

use `nvidia-smi` to check GPU status

In [6]:
import torch
torch.cuda.is_available()  # check if CUDA is available

True

In [7]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cuda


In [8]:
# Count number of devices
torch.cuda.device_count()

1

For PyTorch since it's capable of running compute on the GPU or CPU, it's best to practice to setup device agnostic code.

E.g. run on GPU if available, else run on CPU.

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU, is becauase GPU results in faster computations

In [9]:
# Create a tensor (default is CPU)
tensor = torch.Tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1., 2., 3.]) cpu


In [10]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1., 2., 3.], device='cuda:0') cuda:0


### 4. Moving tensors back to the cpu

In [14]:
# If tensor is on GPU, can't transform it to NumPy directly, use tensor.cpu()
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1., 2., 3.], dtype=float32)

## Exercies & Extra-curriculum

In [22]:
tensor_1 = torch.rand(7, 7)
tensor_2 = torch.rand(1, 7)
torch.matmul(tensor_1, tensor_2.T)

tensor([[2.4911],
        [2.1696],
        [1.5092],
        [1.6439],
        [2.3490],
        [1.4221],
        [1.1739]])

In [23]:
torch.manual_seed(0)
tensor_1 = torch.rand(7, 7)
torch.manual_seed(0)
tensor_2 = torch.rand(1, 7)
torch.matmul(tensor_1, tensor_2.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [35]:
torch.manual_seed(1234)
tensor_1 = torch.rand(2, 3).to(device)
torch.manual_seed(1234)
tensor_2 = torch.rand(2, 3).to(device)
output = torch.matmul(tensor_1, tensor_2.T)

In [36]:
output.max()

tensor(0.6287, device='cuda:0')

In [37]:
output.min()

tensor(0.2161, device='cuda:0')

In [38]:
output.argmax()

tensor(3, device='cuda:0')

In [39]:
output.argmin()

tensor(1, device='cuda:0')

In [51]:
torch.manual_seed(7)
rand_tensor = torch.rand(1, 1, 1, 10)
output_rand = rand_tensor.squeeze()
output_rand, output_rand.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))