## Pytorch Fundamentals - 00
https://www.youtube.com/watch?v=V_xro1bcAuA&t=2598s

In [49]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


## Pytorch sensors 
Created using `torch.Tensor()`
https://docs.pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html

In [50]:
# Scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [51]:
scalar.ndim  # number of dimensions

0

In [52]:
scalar.item()  # get the value as a standard Python number

7

In [53]:
# Vector tensor
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [54]:
vector.shape

torch.Size([2])

In [55]:
vector.ndim

1

In [56]:
# MATRIX
MATRIX = torch.Tensor([[7, 8], 
                        [9, 10]])
MATRIX

tensor([[ 7.,  8.],
        [ 9., 10.]])

In [57]:
MATRIX.ndim #ndim = elements in array

2

In [58]:
MATRIX[1]

tensor([ 9., 10.])

In [59]:
MATRIX.shape

torch.Size([2, 2])

In [60]:
# TENSOR
TENSOR = torch.Tensor([[[1, 2, 3], 
                        [3, 6, 9], 
                        [2, 4, 5]]])
TENSOR

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 5.]]])

In [61]:
TENSOR.ndim

3

In [62]:
TENSOR.shape

torch.Size([1, 3, 3])

In [63]:
TENSOR[0]

tensor([[1., 2., 3.],
        [3., 6., 9.],
        [2., 4., 5.]])

In [64]:
MY_TENSOR = torch.Tensor([[[[1, 2, 3], 
                            [2, 3, 4],
                            [5, 6, 7]]]])
MY_TENSOR.ndim

4

In [65]:
MY_TENSOR.shape

torch.Size([1, 1, 3, 3])

### Random Tensors
https://youtu.be/V_xro1bcAuA?si=g-yVMRmg3KtPZYm6&t=5865

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [66]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2081, 0.6883, 0.6787, 0.1191],
        [0.2886, 0.0818, 0.0798, 0.8789],
        [0.8610, 0.9763, 0.3579, 0.4772]])

In [67]:
random_tensor.ndim

2

In [68]:
random_tensor.shape

torch.Size([3, 4])

In [69]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # height, width, color_channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones


In [70]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [71]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [72]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [73]:
ones.dtype

torch.float32

### Creating a range of tensors

In [74]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
# Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
**Note** Tensor datatypes is one of the three big errors you'll run into with PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
dtype=torch.float32, #datatype - precision in computing, how much detail is stored in memory
device=None, # What device is the tensor stored on?
requires_grad=False) # whether or not to track gradients for this tensor's operations
float_32_tensor

tensor([3., 6., 9.])

In [77]:
float_32_tensor.dtype

torch.float32

In [78]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
d = float_16_tensor * float_32_tensor # becomes float32

torch.float32

## Ints
https://youtu.be/V_xro1bcAuA?si=FeZ6J8jf4MvAp_Zh&t=7409

In [81]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [83]:
y = float_32_tensor * int_32_tensor
y.dtype

torch.float32

### Getting info from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [86]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6519, 0.9086, 0.9461, 0.1746],
        [0.3442, 0.1357, 0.3744, 0.9680],
        [0.5918, 0.6486, 0.4932, 0.9554]])

In [87]:
print(some_tensor)
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

tensor([[0.6519, 0.9086, 0.9461, 0.1746],
        [0.3442, 0.1357, 0.3744, 0.9680],
        [0.5918, 0.6486, 0.4932, 0.9554]])
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [90]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [91]:
# Divide tensor by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [92]:
# Subtract 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [93]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)  # multiply tensor by 10

tensor([10, 20, 30])

### Matrix Multiplication
https://youtu.be/V_xro1bcAuA?si=-YlZWxh2QmpDqDR-&t=8269